language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true

after_success:
- mvn clean

# use latest java version available instead of travis default
#addons:
#  apt:
#   packages:
#    - oracle-java8-installer


notifications:
  email:
  - sendythaker@gmail.com

webhooks:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always

sudo: required