language: java

jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true

after_success:
- mvn sonar:sonar -Dsonar.projectKey=sandeepthaker_java-design-patterns -Dsonar.organization=sandeepthaker-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dcf7a6ba80ffdb822833adc0446f82bb2b459fad

# use latest java version available instead of travis default
#addons:
#  apt:
#   packages:
#    - oracle-java8-installer


notifications:
  email:
  - sendythaker@gmail.com

webhooks:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always

sudo: required